### ISSUE TITLE
Inference Cost calculation bug with pruned quantized model

### ISSUE THREAD

**Issue by sdittmeier** [fastmachinelearning/qonnx#49]
## Prerequisites
qonnx was installed via `pip install qonnx` in my environment.
Onnx files before and after pruning are attached in the .zip file.
pruning_0_clean.onnx is an unpruned model
pruning_1_clean.onnx is a pruned model

## Quick summary
I wanted to calculate BOPs using inference_cost for a model that is pruned iteratively. I expected after each pruning step that the number of BOPs and total_mem_w_bits decreases, but I observed the same values before and after pruning.

Here is a short part of the code showing the relevant calls to the qonnx tools, and a few steps ahead regarding pruning removal and export:
`model_copy = copy.deepcopy(model) # necessary for the export to work properly to be able to continue pruning on the model itself
parameters_to_prune_copy = [(model_copy.network[1], "weight"), (model_copy.network[4], "weight"), (model_copy.network[7], "weight"), (model_copy.network[10], "weight"), (model_copy.network[13], "weight")] # list of pruned layers
for paras in parameters_to_prune_copy:
    prune.remove(paras[0], name = 'weight')  # necessary for the export to work properly with a pruned model
BrevitasONNXManager.export(model_copy, export_path = export_path, input_t = input_quant_tensor, export_params="True")
cleanup(export_path, out_file=export_path_cleanup) # : relevant qonnx calls
inference_cost(export_path_cleanup, output_json = export_json, discount_sparsity = True)`

### Expected behavior
When investigating in https://github.com/fastmachinelearning/qonnx/blob/29cabe4fe60a68091b7a49220c04b24b0d0b936a/src/qonnx/analysis/inference_cost.py#L140 , I found that the quantized weight matrix was not initialized with constant values, `inp1_is_const` returned `None`. 

### Possible fix
Replacing this line https://github.com/fastmachinelearning/qonnx/blob/29cabe4fe60a68091b7a49220c04b24b0d0b936a/src/qonnx/util/inference_cost.py#L91 
`model = model.transform(FoldConstants())`
with this 
`model = model.transform(FoldConstants(exclude_op_types=[]))`
seem to have done the job. 

### Additional context
[pruning_clean_onnx.zip](https://github.com/fastmachinelearning/qonnx/files/11048843/pruning_clean_onnx.zip)

**Comment by HenniOVP** [comment]
To give a little bit of context to the how the fix works: Way back in the past the `FoldConstants` transformations would also fold `Quant` and `BiploarQuant` nodes, because they are technically 'constant' nodes and they weren't yet fully integrated into finn-base back then. However, nowadays these nodes aren't folded away anymore since they contain vital quantization information, that is otherwise lost. 
Unfortunately, for the analysis pass this now means that it would need to traverse the graph further to find the actual weight initializer. Which currently isn't done as @sdittmeier highlighted: https://github.com/fastmachinelearning/qonnx/blob/29cabe4fe60a68091b7a49220c04b24b0d0b936a/src/qonnx/analysis/inference_cost.py#L140

So a potential fix might be to have the analysis pass traverse the graph further. However, I don't know if this would solve the issue entirely, since this would disregard any `zero_point` setting of the `Quant` node, effectively making pruning settings undetectable in some cases. One would instead need to actually execute the `Quant` node.

As such maybe having the `Quant` and `BiploarQuant` nodes constant folded as done by @sdittmeier is indeed the better way to fix the CLI-utility, as this takes care of any `zero_point` settings. However, this would explicitly not fix the bug for the analysis pass itself.
