### ISSUE TITLE
Inference cost calculation bug with quantized model

### ISSUE THREAD

**Issue by sdittmeier** [fastmachinelearning/qonnx#51]
## Prerequisites
qonnx was installed via pip install qonnx

example onnx file:
[pruning_clean_onnx(1).zip](https://github.com/fastmachinelearning/qonnx/files/11260300/pruning_clean_onnx.1.zip)

## Quick summary
Using a quantized network trained with Brevitas, I expected the calculation of BOPs to depend on the number of bits used in the quantized layers (QuantLinear and QuantReLU). However, I always got the same BOPs for any chosen quantization. I found that the underlying data type that was picked up here
https://github.com/fastmachinelearning/qonnx/blob/main/src/qonnx/analysis/inference_cost.py#L126
was always Float32.

## Details
Please add to the following sections to describe the bug as accurately as possible.

### Steps to Reproduce
Can be reproduced using the inference_cost util

### Expected behavior
An output that was sensitive to bit widhts, as
```
{
  "discount_sparsity": true,
  "mem_o_FLOAT32": 38011120.0,
  "mem_w_INT2": 367468.0,
  "mem_w_INT6": 12076.0,
  "op_mac_INT10_INT6": 111357820.0,
  "op_mac_UINT6_INT2": 4509484280.0,
  "op_mac_UINT6_INT6": 111468532.0,
  "op_mac_UINT8_INT2": 2271035256.0,
  "total_bops": 101144711808.0,
  "total_mem_o_bits": 1216355840.0,
  "total_mem_w_bits": 807392.0,
  "unsupported": "set()"
}
```

### Actual behavior
What I got was not sensitive to bit widths, only giving op_mac_FLOAT32

### Possible fix
@HenniOVP found a fix for it, I'd leave it to him to elaborate on that.

**Comment by HenniOVP** [comment]
Thanks @sdittmeier for posting this issue!
So the bug is similar on nature to #49, in the sense that it also stems from a change in how the standard QONNX transformations operated back then and now and how the inference cost function works with an outdated assumption of what these transformations do.

However, compared to the previous issue this one isn't as easily fixed. What happens under the hood is that the inference cost function expects QONNX to attach FINN output datatypes to the QONNX nodes, equivalent to their bitwidth. However, since some time now QONNX nodes will often return a FLOAT type here, when the data is scaled or zero-shifted during fake-quantization. In more detail the function that has changed significantly, and which causes this mismatch in assumptions is the following: https://github.com/fastmachinelearning/qonnx/blob/12c96a3ded06beacab08e0f554e4ed014476c0aa/src/qonnx/custom_op/general/quant.py#L216
It should be noted that the "new" behavior of this function is nowadays as expected, but was simply different during development.

To reproduce "old" behavior as expected by the cost inference function one needs to add a new transformation, which enforces the FINN datatypes depending on the Node bitwidth. An example implementation is given below:

```python
import qonnx.custom_op.registry as registry
from qonnx.core.datatype import DataType
from qonnx.transformation.base import Transformation
from qonnx.util.basic import get_by_name, is_finn_op

class ForceFinnDataTypes(Transformation):
    """Forces the FINN datatype for all Quant and BiploarQuant nodes."""

    def apply(self, model):
        graph = model.graph
        graph_modified = False
        for node in graph.node:
            graph_modified |= _infer_node_datatype(model, node)
        return (model, graph_modified)

def _infer_node_datatype(model, node):
    """Infer output datatype(s) for a particular node. Returns True if any
    changes were made.
    Forces the FINN datatype for all Quant and BiploarQuant nodes.
    Basically a short-circuited implementation of this: https://github.com/fastmachinelearning/qonnx/blob/12c96a3ded06beacab08e0f554e4ed014476c0aa/src/qonnx/transformation/infer_datatypes.py#L128
    and this: https://github.com/fastmachinelearning/qonnx/blob/12c96a3ded06beacab08e0f554e4ed014476c0aa/src/qonnx/custom_op/general/quant.py#L222
    """
    odtypes = list(map(lambda x: model.get_tensor_datatype(x), node.output))
    if is_finn_op(node.domain):
        # handle DataType inference for CustomOp
        try:
            # lookup op_type in registry of CustomOps
            inst = registry.getCustomOp(node)
            try:
                # This will only work for QONNX Quant and BipolarQuant nodes
                finn_dt = inst.get_integer_datatype(model)
                model.set_tensor_datatype(node.output[0], finn_dt)
            except AttributeError:
                pass
        except KeyError:
            # exception if op_type is not supported
            raise Exception("Custom op_type %s is currently not supported." % op_type)
    else:
        pass
    
    # compare old and new output dtypes to see if anything changed
    new_odtypes = list(map(lambda x: model.get_tensor_datatype(x), node.output))
    graph_modified = new_odtypes != odtypes
    return graph_modified

def compute_bops(inf_cost_dict):
    total_bops = 0.0
    for (k, v) in inf_cost_dict.items():
        if k.startswith("op_mac"):
            comps = k.split("_")
            dt1 = DataType[comps[2]]
            dt2 = DataType[comps[3]]
            total_bops += dt1.bitwidth() * dt2.bitwidth() * v
    return total_bops


def compute_mem_bits(inf_cost_dict, filter_string="mem_w"):
    total_mem_bits = 0.0
    for (k, v) in inf_cost_dict.items():
        if k.startswith(filter_string):
            comps = k.split("_")
            dt = DataType[comps[2]]
            total_mem_bits += dt.bitwidth() * v
    return total_mem_bits
```

This new transformation is roughly a equivalent to a short-circuited implementation of this: https://github.com/fastmachinelearning/qonnx/blob/12c96a3ded06beacab08e0f554e4ed014476c0aa/src/qonnx/transformation/infer_datatypes.py#L128 and this: https://github.com/fastmachinelearning/qonnx/blob/12c96a3ded06beacab08e0f554e4ed014476c0aa/src/qonnx/custom_op/general/quant.py#L222

With this the inference cost function returns numbers as expected. A full example, that works with the network, which @sdittmeier had posted in #49 and also in this issue (I think) can be found in the following zip-compressed notebook: [Bops_deving.ipynb.zip](https://github.com/fastmachinelearning/qonnx/files/11260858/Bops_deving.ipynb.zip)

**Comment by maltanar** [comment]
Thanks for the detailed report. This bug has been around for a while and in fact we've had a solution for this prior to `finn-base` (specifically the [ITU competition branch](https://github.com/Xilinx/finn-base/tree/feature/itu_competition_21)) migrating to `qonnx`, but that got left behind. 

In short, instead of marking the datatypes from `Quant` nodes as `FLOAT32` we can refine this one step further to indicate that they are scaled integers (where the scale may be tensor- or channel-wise). There are some intricacies involved with putting fully-fledged scaled integer datatypes into the qonnx toolkit (we would have to capture the scale factor itself as part of the datatype, which gets a bit verbose...) but just to a have a fix for the inference cost, I brought back the simplified form of scaled integers (e.g. just `SCALEDINT<4>` into `qonnx`) with this branch:

https://github.com/fastmachinelearning/qonnx/tree/feature/scaledint_inference_cost

Using this branch, I get the following output:

```
(venv) yamanu70:qonnx yamanu$ qonnx-inference-cost pruning_1_clean.onnx --discount-sparsity False
Inference cost for pruning_1_clean.onnx
{
  "discount_sparsity": false,
  "mem_o_INT32": 38011120.0,
  "mem_w_SCALEDINT<2>": 0.0,
  "mem_w_SCALEDINT<6>": 0.0,
  "op_mac_SCALEDINT<10>_SCALEDINT<6>": 113369088.0,
  "op_mac_SCALEDINT<6>_SCALEDINT<2>": 9674162176.0,
  "op_mac_SCALEDINT<6>_SCALEDINT<6>": 113369088.0,
  "op_mac_SCALEDINT<8>_SCALEDINT<2>": 4837081088.0,
  "total_bops": 204366675968.0,
  "total_mem_o_bits": 1216355840.0,
  "total_mem_w_bits": 0.0,
  "unsupported": "set()"
}
```

Can you confirm that this behaves as expected?

**Comment by sdittmeier** [comment]
Thanks @maltanar for looking into this!
Comparing to what is under Expected Behaviour in the issue description, the calculations of `op_macs` and `bops` looks reasonable, with `discount_sparsity: false`.
It seems the calculation of memory bits is affected though in the fix, giving only 0's.

**Comment by maltanar** [comment]
The issue for the memory bits actually turned out to be the same as the cause of #49 - for which I think the best fix is simply call `FoldConstants(exclude_op_types=[])` as you suggested for that issue, so I've included that in the `feature/scaledint_inference_cost` branch. We now seem to get proper behavior for memory bits, and the issue affecting the sparsity also seems to be fixed, see below:

```
(venv) yamanu70:qonnx yamanu$ qonnx-inference-cost pruning_1_clean.onnx --discount-sparsity False
Inference cost for pruning_1_clean.onnx
{
  "discount_sparsity": false,
  "mem_o_INT32": 38011120.0,
  "mem_w_SCALEDINT<2>": 786432.0,
  "mem_w_SCALEDINT<6>": 12288.0,
  "op_mac_SCALEDINT<10>_SCALEDINT<6>": 113369088.0,
  "op_mac_SCALEDINT<6>_SCALEDINT<2>": 9674162176.0,
  "op_mac_SCALEDINT<6>_SCALEDINT<6>": 113369088.0,
  "op_mac_SCALEDINT<8>_SCALEDINT<2>": 4837081088.0,
  "total_bops": 204366675968.0,
  "total_mem_o_bits": 1216355840.0,
  "total_mem_w_bits": 1646592.0,
  "unsupported": "set()"
}

(venv) yamanu70:qonnx yamanu$ qonnx-inference-cost pruning_1_clean.onnx --discount-sparsity True
Inference cost for pruning_1_clean.onnx
{
  "discount_sparsity": true,
  "mem_o_INT32": 38011120.0,
  "mem_w_SCALEDINT<2>": 205439.0,
  "mem_w_SCALEDINT<6>": 7347.0,
  "op_mac_SCALEDINT<10>_SCALEDINT<6>": 101781232.0,
  "op_mac_SCALEDINT<6>_SCALEDINT<2>": 2507589896.0,
  "op_mac_SCALEDINT<6>_SCALEDINT<6>": 33785612.0,
  "op_mac_SCALEDINT<8>_SCALEDINT<2>": 1283170532.0,
  "total_bops": 57944963216.0,
  "total_mem_o_bits": 1216355840.0,
  "total_mem_w_bits": 454960.0,
  "unsupported": "set()"
}
```

**Comment by sdittmeier** [comment]
I can reproduce the exact same result on my side.
This looks good, thanks 👍
